name: PixelOS-Bot
on:
  schedule:
    - cron: '0 */05 * * *'
  workflow_dispatch:

env:
  BOT_API: ${{ secrets.BOT_API }}
  TOKEN: ${{ secrets.GH_PAT }}
  GITHUB_TOKEN: ${{ secrets.GH_PAT }}

jobs:
  postman:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dep
        run: sudo pip install python-telegram-bot
      
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          repository: PixelOS-Releases/MaintainerBot
          token: ${{ secrets.GH_PAT }}
          path: MaintainerBot
      
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          repository: PixelOS-Releases/releases 
          token: ${{ secrets.GH_PAT }}
          path: releases

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          repository: PixelOS-Pixelish/official_devices
          token: ${{ secrets.GH_PAT }}
          path: PixelOS-Pixelish/official_devices
      
      - name: Bot
        run: sudo -E python3 MaintainerBot/MaintainerBot &> /dev/null
